require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'FileAccess', :path => '../../../file-access'
end

target 'App' do
  capacitor_pods
  # Embedded HTTP server used by AnkiBridgePlugin to expose media files
  # at http://127.0.0.1:<port>/... so AnkiMobile can fetch them via the
  # anki://x-callback-url/addnote field URLs. Same approach Manatan uses.
  pod 'GCDWebServer', '~> 3.5.4'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
